### ISSUE TITLE
class path resource [countries.csv] cannot be resolved to absolute file path because it does not ...

### ISSUE THREAD

**Issue by seppaleinen** [seppaleinen/worldinmovies#5]
ClassPathResource doesn't work when packaged into a jarfile..

https://sentry.io/david-eriksson/Worldinmovies/issues/166358170/

```
Stacktrace (most recent call first):

    at se.david.backend.controllers.services.util.CountriesImporter.importCountries(CountriesImporter.java:38)
    at se.david.backend.controllers.services.ImportService.importCountries(ImportService.java:53)
    at se.david.backend.controllers.ImportController.importCountries(ImportController.java:25)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)

class path resource [countries.csv] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app.jar!/BOOT-INF/classes!/countries.csv
```

**Comment by seppaleinen** [comment]
resource.getFile() doesn't work when the file is embedded in the jar.. resource.getInputStream works instead
